version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgresDB
    environment:
      POSTGRES_DB: speer
      POSTGRES_USER: keshav
      POSTGRES_PASSWORD: keshav
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  postgres_data:
