// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	model "github.com/keshu12345/notes/model"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// SingInUser provides a mock function with given fields: c
func (_m *AuthService) SingInUser(c *gin.Context) (string, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for SingInUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context) (string, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context) string); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SingUpUser provides a mock function with given fields: c
func (_m *AuthService) SingUpUser(c *gin.Context) (model.User, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for SingUpUser")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context) (model.User, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context) model.User); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
